export const keenIcons = {
  learn: 'teacher',
  course: 'book-open',
  courses: 'book-open',
  blog: 'note-2',
  test: 'tablet-ok',
  tests: 'tablet-ok',
  challenge: 'abstract-22',
  challenges: 'abstract-22',
  problem: 'message-programming',
  problems: 'message-programming',
  practice: 'abstract-45',
  competition: 'cup',
  competitions: 'cup',
  tournament: 'award',
  tournaments: 'award',
  arena: 'shield',
  contest: 'flag',
  contests: 'flag',
  users: 'profile-user',
  todo: 'check-square',

  profile: 'user-tick',
  rating: 'chart-simple-2',
  attempt: 'filter-tick',
  attempts: 'filter-tick',
};
